#!/usr/bin/env bash
# Install nginx
# listening on port 80

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
