#!/usr/bin/env bash
set -e

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Check if Nginx is already installed
if! dpkg -s nginx &> /dev/null; then
    echo "Nginx is not installed, skipping..."
else
    # starting nginx service
    sudo service nginx start

    # Check if firewall is enabled
    if! sudo ufw status | grep -q "enabled"; then
        sudo ufw enable
    fi

    # allowing nginx on firewall
    sudo ufw allow 'Nginx HTTP'

    # Give the user ownership to website files for easy editing
    sudo chown -R "$USER":"$USER" /var/www/html
    sudo chmod -R 755 /var/www

    # Backup default index
    cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

    # Creating new index
    echo "Hello World!" > /var/www/html/index.nginx-debian.html

    # Restarting nginx
    sudo service nginx restart
fi

echo -e "\nCompleted. ✅\n"
