#!/usr/bin/env bash
# Configure nginx in a new Ubuntu machine with a permanent redirect

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

new_config=$(cat <<EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \\\$uri \\\$uri/ =404;
        }
        
        if (\$request_filename ~* redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
EOF
)

echo -e "$new_config\n" > /etc/nginx/sites-available/default

nginx_pid=$(pgrep nginx)
if [ -n "$nginx_pid" ]; then
    service nginx restart
else
    service nginx start
fi
