#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

k=0

while [ $k -lt 10 ]
do
  if [ $k -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( k++ ))
done
